# =============================================================================
# Docker Compose file for testing on Go versions 1.18, 1.19 and latest.
# =============================================================================
# It is recommended to run specifying a specific Go version and not at once.
#
# Since the service `tidy` will update/re-write the "go.mod" file to the latest
# version, during it's process the "go.mod" file will be gone temporarily. Thus,
# it will cause failure in the other container becaue of missing "go.mod" file.
#
# Recommended usage:
#   docker compose --file ./.github/docker-compose.yml run tidy && \
#   docker compose --file ./.github/docker-compose.yml run v1_18
#
# NOT recommended to run all tests at once whith "up":
#   docker compose --file ./.github/docker-compose.yml up
version: "3.9"
services:
  # Service tidy updates the go.mod to the latest
  tidy:
    build:
      context: ..
      dockerfile: ./.github/Dockerfile
      args:
        VARIANT: 1.22-alpine
    volumes:
      - ..:/workspaces
    entrypoint: [ "./.github/go-mod-tidy.sh" ]
  # Service v1_22 runs the tests on Go v1.22. The minimum supported version
  v1_22:
    build:
      context: ..
      dockerfile: ./.github/Dockerfile
      args:
        VARIANT: 1.22-alpine
    volumes:
      - ..:/workspaces
  # Service latest runs the tests on latest Go docker image
  latest:
    build:
      context: ..
      dockerfile: ./.github/Dockerfile
      args:
        VARIANT: alpine
    volumes:
      - ..:/workspaces
