run:
  tests: true
  build-tags:
    - golangci
  allow-parallel-runners: true
issues:
  exclude-dirs:
    - .github
    - .vscode

output:
  sort-results: true

linters:
  enable-all: true
  disable:
  # Remove deprecated linters that are deacivated
  #- structcheck
  #- scopelint
  #- ifshort
  #- interfacer
  #- maligned
  #- exhaustivestruct
  #- nosnakecase
  #- varcheck
  #- deadcode
  #- golint
  #- gomnd
  #- execinquery
  #
  # Disable deprecated/abandoned linters
  - exportloopref
  # Allow global variables
  - gochecknoglobals
  # Disable due to use of external linters
  - depguard

linters-settings:
  cyclop:
    # The maximal code complexity to report (Default: 10).
    max-complexity: 15
