# This workflow runs the unit test (`go test ./...`) on vaious platforms,
# such as: Linux, macOS and Windows.
name: Unit Tests

on:
  workflow_dispatch:
  pull_request:

jobs:
  coverage:
    name: Unit test

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Run unit test
        run: |
          go mod download
          go test -race -v ./...
