# Details of this action see: https://github.com/golangci/golangci-lint-action
name: golangci-lint

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: 'stable'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v1.64
          # Optional: golangci-lint command line arguments.
          args: --config ./.golangci.yml
