# =============================================================================
#  Release Assets and Homebrew's Tap
# =============================================================================
# This workflow will build the binaries and push the archives to the assets in
# the releases page if a release was created. Then pushes the tap config file
# for Homebrew tap. See: ../../.goreleaser.yml
name: Release

on:
  workflow_dispatch:
  release:
    types:
      - created
    tags:
      - 'v*'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --config .goreleaser.yml
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
